services:
  minio:
    image: minio/minio:latest
    container_name: minio_app
    environment:
     - MINIO_ROOT_USER:minioadmin
      -MINIO_ROOT_PASSWORD:minioadmin

    command: server /data --console-address ":9001"




  minio-sp:
    image: minio/mc:latest
    container_name: minio_boot
    depends_on:
      - minio
    entrypoint: >
      bin/sh/ -c "
      sleep 5;
      mc alias set minio http://minio:9000 minioadmin
      mc mb -p minio/files || true
      echo
      "
