services:
  minio:
    image: minio/minio:latest
    container_name: minio_duman
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin

    command: server /data --console-address

